Number of literals: 419
Constructing lookup tables: [10%] [20%] [30%] [40%] [50%] [60%] [70%] [80%] [90%] [100%]
Post filtering unreachable actions:  [10%] [20%] [30%] [40%] [50%] [60%] [70%] [80%] [90%] [100%]
[01;34mNo analytic limits found, not considering limit effects of goal-only operators[00m
Pruning (goto_waypoint robot_assistant wp13 wp0) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp33 wp0) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp13 wp1) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp13 wp10) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp23 wp11) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp53 wp11) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp13 wp12) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp0 wp13) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp1 wp13) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp10 wp13) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp12 wp13) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp16 wp13) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp2 wp13) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp28 wp13) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp3 wp13) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp33 wp13) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp4 wp13) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp5 wp13) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp8 wp13) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp9 wp13) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp23 wp14) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp53 wp14) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp13 wp16) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp43 wp16) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp23 wp18) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp53 wp18) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp23 wp19) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp53 wp19) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp13 wp2) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp23 wp20) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp33 wp21) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp23 wp22) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp43 wp22) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp11 wp23) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp14 wp23) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp18 wp23) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp19 wp23) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp20 wp23) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp22 wp23) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp27 wp23) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp28 wp23) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp29 wp23) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp30 wp23) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp32 wp23) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp34 wp23) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp35 wp23) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp41 wp23) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp42 wp23) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp46 wp23) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp52 wp23) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp53 wp23) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp6 wp23) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp7 wp23) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp33 wp24) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp33 wp25) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp33 wp26) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp23 wp27) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp13 wp28) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp23 wp28) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp33 wp28) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp23 wp29) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp33 wp29) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp53 wp29) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp13 wp3) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp23 wp30) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp43 wp30) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp33 wp31) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp23 wp32) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp33 wp32) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp0 wp33) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp13 wp33) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp21 wp33) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp24 wp33) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp25 wp33) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp26 wp33) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp28 wp33) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp31 wp33) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp32 wp33) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp34 wp33) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp36 wp33) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp37 wp33) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp43 wp33) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp8 wp33) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp23 wp34) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp33 wp34) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp13 wp35) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp23 wp35) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp33 wp35) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp53 wp35) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp33 wp36) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp43 wp36) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp33 wp37) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp43 wp37) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp43 wp38) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp53 wp39) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp13 wp4) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp23 wp41) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp53 wp41) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp13 wp42) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp23 wp42) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp53 wp42) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp16 wp43) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp22 wp43) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp30 wp43) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp33 wp43) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp36 wp43) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp37 wp43) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp38 wp43) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp45 wp43) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp46 wp43) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp47 wp43) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp48 wp43) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp49 wp43) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp50 wp43) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp51 wp43) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp53 wp43) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp54 wp43) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp55 wp43) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp56 wp43) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp53 wp44) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp43 wp45) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp53 wp45) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp23 wp46) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp43 wp46) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp53 wp46) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp43 wp47) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp53 wp47) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp43 wp48) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp53 wp48) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp43 wp49) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp53 wp49) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp13 wp5) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp43 wp50) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp53 wp50) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp43 wp51) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp53 wp51) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp23 wp52) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp43 wp52) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp53 wp52) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp11 wp53) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp14 wp53) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp18 wp53) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp19 wp53) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp23 wp53) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp29 wp53) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp35 wp53) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp39 wp53) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp41 wp53) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp42 wp53) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp43 wp53) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp44 wp53) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp45 wp53) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp46 wp53) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp47 wp53) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp48 wp53) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp49 wp53) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp50 wp53) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp51 wp53) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp52 wp53) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp7 wp53) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp43 wp54) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp43 wp55) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp43 wp56) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp23 wp6) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp23 wp7) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp13 wp8) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp33 wp8) - never appeared in initial RPG
Pruning (goto_waypoint robot_assistant wp13 wp9) - never appeared in initial RPG
Pruning (scan_place robot_assistant wp13) - never appeared in initial RPG
Pruning (scan_place robot_assistant wp23) - never appeared in initial RPG
Pruning (scan_place robot_assistant wp33) - never appeared in initial RPG
Pruning (scan_place robot_assistant wp43) - never appeared in initial RPG
Pruning (scan_place robot_assistant wp53) - never appeared in initial RPG
Pruning (grasp_object robot_assistant mug wp13) - never appeared in initial RPG
Pruning (grasp_object robot_assistant paper wp13) - never appeared in initial RPG
Pruning (grasp_object robot_assistant post1 wp13) - never appeared in initial RPG
Pruning (grasp_object robot_assistant post2 wp13) - never appeared in initial RPG
Pruning (grasp_object robot_assistant mug wp23) - never appeared in initial RPG
Pruning (grasp_object robot_assistant paper wp23) - never appeared in initial RPG
Pruning (grasp_object robot_assistant post1 wp23) - never appeared in initial RPG
Pruning (grasp_object robot_assistant post2 wp23) - never appeared in initial RPG
Pruning (grasp_object robot_assistant mug wp33) - never appeared in initial RPG
Pruning (grasp_object robot_assistant paper wp33) - never appeared in initial RPG
Pruning (grasp_object robot_assistant post1 wp33) - never appeared in initial RPG
Pruning (grasp_object robot_assistant post2 wp33) - never appeared in initial RPG
Pruning (grasp_object robot_assistant mug wp43) - never appeared in initial RPG
Pruning (grasp_object robot_assistant paper wp43) - never appeared in initial RPG
Pruning (grasp_object robot_assistant post1 wp43) - never appeared in initial RPG
Pruning (grasp_object robot_assistant post2 wp43) - never appeared in initial RPG
Pruning (grasp_object robot_assistant mug wp53) - never appeared in initial RPG
Pruning (grasp_object robot_assistant paper wp53) - never appeared in initial RPG
Pruning (grasp_object robot_assistant post1 wp53) - never appeared in initial RPG
Pruning (grasp_object robot_assistant post2 wp53) - never appeared in initial RPG
Pruning (place_object robot_assistant mug wp13) - never appeared in initial RPG
Pruning (place_object robot_assistant paper wp13) - never appeared in initial RPG
Pruning (place_object robot_assistant post1 wp13) - never appeared in initial RPG
Pruning (place_object robot_assistant post2 wp13) - never appeared in initial RPG
Pruning (place_object robot_assistant mug wp23) - never appeared in initial RPG
Pruning (place_object robot_assistant paper wp23) - never appeared in initial RPG
Pruning (place_object robot_assistant post1 wp23) - never appeared in initial RPG
Pruning (place_object robot_assistant post2 wp23) - never appeared in initial RPG
Pruning (place_object robot_assistant mug wp33) - never appeared in initial RPG
Pruning (place_object robot_assistant paper wp33) - never appeared in initial RPG
Pruning (place_object robot_assistant post1 wp33) - never appeared in initial RPG
Pruning (place_object robot_assistant post2 wp33) - never appeared in initial RPG
Pruning (place_object robot_assistant mug wp43) - never appeared in initial RPG
Pruning (place_object robot_assistant paper wp43) - never appeared in initial RPG
Pruning (place_object robot_assistant post1 wp43) - never appeared in initial RPG
Pruning (place_object robot_assistant post2 wp43) - never appeared in initial RPG
Pruning (place_object robot_assistant mug wp53) - never appeared in initial RPG
Pruning (place_object robot_assistant paper wp53) - never appeared in initial RPG
Pruning (place_object robot_assistant post1 wp53) - never appeared in initial RPG
Pruning (place_object robot_assistant post2 wp53) - never appeared in initial RPG
99% of the ground temporal actions in this problem are compression-safe
Initial heuristic = 6.000
b (5.000 | 2.500)b (4.000 | 17.501)b (3.000 | 38.502)b (2.000 | 76.503)b (1.000 | 88.504);;;; Solution Found
; States evaluated: 8
; Cost: 95.505
; Time 0.08
0.000: (place_object robot_assistant post1 wp6)  [2.500]
2.501: (goto_waypoint robot_assistant wp6 wp19)  [15.000]
17.502: (goto_waypoint robot_assistant wp19 wp28)  [21.000]
38.503: (goto_waypoint robot_assistant wp28 wp3)  [38.000]
76.504: (goto_waypoint robot_assistant wp3 wp2)  [12.000]
88.505: (goto_waypoint robot_assistant wp2 wp1)  [7.000]
